# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pickle
from Traitement import traitement
from vectorial import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        infile=open('pkl/relevant_docs.pkl','rb')
        self.relevant_docs=pickle.load(infile)
        infile.close()
        infile=open('pkl/queries.pkl','rb')
        self.queries=pickle.load(infile)
        infile.close()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 710)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Documents/projet/scr/icone_RI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 20, 261, 241))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 239))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, -1, 261, 241))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(300, 20, 281, 241))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 279, 239))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.listWidget_2.setGeometry(QtCore.QRect(190, 470, 281, 341))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_6 = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.listWidget_6.setGeometry(QtCore.QRect(-5, 0, 291, 241))
        self.listWidget_6.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget_6.setFont(font)
        self.listWidget_6.setObjectName("listWidget_6")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(600, 20, 291, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 271, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(610, 280, 301, 141))
        
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 281, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 100, 121, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 100, 141, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label.setObjectName("label")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(610, 440, 291, 271))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 140, 111, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 80, 251, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 140, 121, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 210, 121, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_5.setGeometry(QtCore.QRect(163, 210, 111, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 60, 13))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(170, 190, 60, 13))
        self.label_4.setObjectName("label_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 18, 290, 40))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout.addWidget(self.radioButton_6)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 110, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(5)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setValue(25)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 280, 591, 231))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidget_5 = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_5.setGeometry(QtCore.QRect(10, 30, 571, 191))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget_5.setFont(font)
        self.listWidget_5.setObjectName("listWidget_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_5.setGeometry(QtCore.QRect(600, 130, 301, 131))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 80, 131, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 80, 141, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox.setGeometry(QtCore.QRect(150, 30, 141, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(3041)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 520, 571, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_6)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 30, 431, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setObjectName("listWidget_3")
        self.listWidget_4 = QtWidgets.QListWidget(self.groupBox_6)
        self.listWidget_4.setGeometry(QtCore.QRect(450, 30, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_4.setFont(font)
        self.listWidget_4.setObjectName("listWidget_4")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Recherche d\'information"))
        self.groupBox.setTitle(_translate("MainWindow", "Indexation"))
        self.radioButton.setText(_translate("MainWindow", "Afficher par docs"))
        self.pushButton_2.setText(_translate("MainWindow", "Indexe pondéré"))
        self.radioButton_2.setText(_translate("MainWindow", "Afficher par mots"))
        self.pushButton.setText(_translate("MainWindow", "Indexe"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Modèle Booléen"))
        self.label_3.setText(_translate("MainWindow", "Requête"))
        self.pushButton_5.setText(_translate("MainWindow", "Recherche"))
        self.label.setText(_translate("MainWindow", "Time"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Modèle Vectoriel et évaluation"))
        self.pushButton_9.setText(_translate("MainWindow", "Evaluation"))
        self.label_7.setText(_translate("MainWindow", "Requête"))
        self.pushButton_8.setText(_translate("MainWindow", "Recherche"))
        self.label_2.setText(_translate("MainWindow", "recall"))
        self.label_4.setText(_translate("MainWindow", "precision"))
        self.radioButton_3.setText(_translate("MainWindow", "I_Prod"))
        self.radioButton_4.setText(_translate("MainWindow", "Dice"))
        self.radioButton_5.setText(_translate("MainWindow", "Cosinus"))
        self.radioButton_6.setText(_translate("MainWindow", "Jaccard"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Résultat du modèle"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Recherche"))
        self.pushButton_3.setText(_translate("MainWindow", "Rechercher le mot"))
        self.pushButton_4.setText(_translate("MainWindow", "Rechercher document"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Fichier query "))
        
        t=traitement()

        # listWidget List 6
        # list_4

        self.pushButton_4.clicked.connect(lambda: t.Fonctions_dacces1(self))
        self.pushButton_3.clicked.connect(lambda: t.Fonctions_dacces2(self))
        self.pushButton.clicked.connect(lambda: t.ChoixAffichage(self,"Index"))
        self.pushButton_2.clicked.connect(lambda: t.ChoixAffichage(self,"IndexP") )
        self.pushButton_9.clicked.connect(lambda: t.evaluation(self, self.horizontalSlider.value()))
        self.pushButton_5.clicked.connect(lambda: t.boolean_query(self))
        self.pushButton_8.clicked.connect(lambda: self.getVectorial())

        for index in self.queries :
            self.listWidget_3.addItem('{}) '.format(index)+self.queries[index])
        
        self.listWidget_3.itemClicked.connect(lambda: self.ItemQueries())

    def getVectorial(self):
        req = self.textEdit_2.toPlainText()

        if self.radioButton_3.isChecked():
            result = inner_product(req, weighted)
        elif self.radioButton_4.isChecked():
            result = dice(req, weighted)
        elif self.radioButton_5.isChecked():            
            result = cosinus(req, weighted)
        elif self.radioButton_6.isChecked():
            result = jaccard(req, weighted)
        else:
            self.radioButton_5.setChecked(True)
            result = cosinus(req, weighted)

        self.listWidget_5.clear()
        [self.listWidget_5.addItem("document:\t"+str(doc[1])+"\t\tpoids:\t"+str(doc[0])) for doc in result]
        pass


    def ItemQueries(self) :
        import re
        self.listWidget_4.clear()
        Doc=self.listWidget_3.currentItem().text()
        num=re.findall('^(\d+)',Doc)[0]
        try:
            for i in self.relevant_docs[int(num)] :
                self.listWidget_4.addItem(i)
        except:
            pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

